apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octopetshop-test
  annotations:
    codefresh.io/product: octopetshop
spec:
  project: default
  source:
    repoURL: https://github.com/twerthi/OctoPetShop.git
    targetRevision: HEAD
    path: k8s/kustomize/deployment/overlays/Test
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true