apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
type: Opaque
stringData:
  sa-password: "wguG*%5I^I8b"
  connectionstring: "Data Source=octopetshop-sqlserver-cluster-ip-service;Initial Catalog=OctoPetShop; User ID=sa; Password=wguG*%5I^I8b"
