apiVersion: batch/v1
kind: Job
metadata:
  name: octopetshop-dbup
  generateName: octopetshop-dbup-
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
#  ttlSecondsAfterFinished: 30 
  template:
    spec:
      containers:
        - name: dbup
          image: octopussamples/octopetshop-database
          #image: octopetshop_database
          #imagePullPolicy: Never
          command: [ "dotnet", "run", "--no-launch-profile" ]
          env:
            - name: DbUpConnectionString
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: connectionstring
      restartPolicy: Never

