apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octopetshop-development
spec:
  project: default
  source:
    repoURL: https://github.com/twerthi/OctoPetShop.git
    targetRevision: HEAD
    path: k8s/kustomize/rollout/overlays/Development
  destination:
    server: https://kubernetes.default.svc
    namespace: development
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true